#!/usr/bin/bash

#----------------------------------------------------------------
# This script is not for execute directly.
# Please use 'source ./setup'.
#----------------------------------------------------------------

export NITROSYSTEM_ROOT=`cygpath -m $PWD`
